device: cuda:0

model:
  name: nablasian.zoo.detection - RetinaNet
  args:
    num_in_ch: 3
    num_classes: 1
    num_anchor_boxes: 9
    path: free_anchor/retinanet.py
    sub_net_depth: 3

anchor_generator:
  name: nablasian.solvers.detection.generators - AnchorGenerator
  args:
    sizes: [20, 40, 80, 160]
    aspect_ratios: [0.5, 1.0, 2.0]
    scale: 3

transforms:
  - name: nablasian.datasets.transforms - Scale
    args:
      size: 800
  - name: nablasian.datasets.transforms - ToTensor
    args:

nms:
  name: nablasian.solvers.detection.nms - NMS
  args:
    score_th: 0.05
    iou_th: 0.5
    preprocess: sigmoid
    pre_max_num_bboxes: 1000
    post_max_num_bboxes: 100
    cls_agnostic: True

coder:
  name: nablasian.solvers.detection.coders - AnchorBoxCoder
  args:
    weights: [10, 10, 5, 5]
